[package]
name = "touchscript_backend"
version = "0.1.0"
authors = ["Nathan Ross <NathanAnthonyRoss19@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
# Tell `rustc` to optimize for small code size.
lto = true
opt-level = "z"
debug = false
panic = "abort"